
def build(bld):
    # TODO ensure that this executes before the tests
    import os
    static_ext = 'static'
    static_files = bld.path.ant_glob('*.' + static_ext)
    for f in static_files:
        src = f.path_from(bld.path)
        dest = os.path.splitext(src)[0]
        bld(rule='${COPY} ${SRC} ${TGT}',
            source=src,
            target=dest)

    tests = [
        ('common', 'common'),
        ('ray', 'ray'),
        ('aabb', 'aabb'),
        ('arealight', 'AreaLight'),
        ('sphere', ['sphere', 'shape']),
        ('triangle', ['triangle', 'shape']),
        ('lightpath', ['lightpath']),
        ('mtl_loader', ['mtl_loader']),
        ('obj_loader', ['obj_loader']),
        ('assimp_loader', ['assimp_loader']),
        ('kdtree', ['kdtree', 'obj_loader']),
        ('cam_loader', ['cam_loader']),
        ('perturb_normals', ['sphere', 'ray'])]

    for t in tests:
        bld.program(
            features='test',
            source='test_' + t[0] + ".cpp",
            target=t[0] + '.test',
            lib=['gtest', 'assimp', 'png'],
            use=t[1])
