def build(bld):
    bld.objects(source='obj_loader.cpp', target='obj_loader', use='mtl_loader triangle solidColor simpleObject')
    bld.objects(source='mtl_loader.cpp', target='mtl_loader', use='solidColor')
