def build(bld):
    import os
    srcs = bld.path.ant_glob('*.cpp')
    for s in srcs:
        src = os.path.basename(s.abspath())
        dest = os.path.splitext(src)[0]
        bld.objects(source=src, target=dest)
