def build(bld):
    bld.objects(source='shape.cpp', target='shape')
    bld.objects(source='triangle.cpp', target='triangle', use='shape common')
    bld.objects(source='sphere.cpp', target='sphere', use='shape common')
