def build(bld):
    from waflib.Tools import waf_unit_test
    bld.add_post_fun(waf_unit_test.summary)
    bld.program(
        source='main.cpp',
        target='renderer',
        use='easypng common camera pathtracer raytracer simpleObject'
        + ' obj_loader assimp_loader log cam_loader metropolis',
        lib=['png', 'assimp'])

    bld.recurse('core')
    bld.recurse('shapes')
    bld.recurse('file_loader')
    bld.recurse('materials')
    bld.recurse('kdtree')
    bld.recurse('render')
    bld.recurse('drawables')
    bld.recurse('lights')
    bld.recurse('util')

    if bld.env.TEST:
        bld.recurse('Tests')
