def build(bld):
    from waflib.Tools import waf_unit_test
    bld.add_post_fun(waf_unit_test.summary)
    bld.program(
            source='main.cpp',
            target='renderer',
            use='easypng common camera pathtracer raytracer obj_loader',
            lib=['png', 'gomp'])

    objects = []

    for obj in objects:
        bld.objects(source=obj+'.cpp', target=obj)

    bld.recurse('core')
    bld.recurse('shapes')
    bld.recurse('file_loader')
    bld.recurse('materials')
    bld.recurse('kdtree')
    bld.recurse('render')
    bld.recurse('drawables')
    bld.recurse('lights')

    if bld.env.TEST:
        bld.recurse('Tests')
